name: Trigger auto deployment for lobechat

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/lobechat-AutoDeployTrigger-9843dbce-a071-41fc-b89e-15adeed227e6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.LOBECHAT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LOBECHAT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LOBECHAT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.LOBECHAT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LOBECHAT_REGISTRY_PASSWORD }}
          containerAppName: lobechat
          resourceGroup: NetworkWatcherRG
          imageToBuild: lsiem/lobechat:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


